{
 "title": "IIND-dashboard",
 "description": "save\n",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Operating Time and Occupation per Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Operating Time per Machine",
     "type": "table",
     "gridPos": { "h": 14, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dataset": "meec00909",
       "rawSql": "-- Total operating time per machine\nSELECT\n    m.name             AS \"Machine\",\n    COALESCE(ms.total_op_time_s, 0) AS \"Total Operating Time\"\nFROM mes.machines m\nLEFT JOIN mes.machine_stats ms\n    ON ms.machine_id = m.machine_id\n    AND ms.recorded_at = (\n        SELECT MAX(recorded_at)\n        FROM mes.machine_stats\n        WHERE machine_id = m.machine_id\n    )\nORDER BY m.name;"
      }
     ]
    },
    {
     "title": "Ocuppation per Machine",
     "type": "gauge",
     "gridPos": { "h": 14, "w": 8, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SET search_path TO mes;\n\nSELECT\n    m.name             AS machine,\n    COALESCE(ROUND(ms.occupation_pct::numeric, 1), 0) AS \"Occupation (%)\"\nFROM machines m\nLEFT JOIN machine_stats ms\n    ON ms.machine_id = m.machine_id\n    AND ms.recorded_at = (\n        SELECT MAX(recorded_at)\n        FROM machine_stats\n        WHERE machine_id = m.machine_id\n    )\nORDER BY m.name;"
      }
     ]
    }
   ]
  },
  {
   "title": "Tool Operation Time per Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cell 1 Tool Usage",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dataset": "meec00909",
       "rawSql": "SELECT\n    m.name                                             AS \"Machine\",\n    t.tool_name                                        AS \"Tool\",\n    COALESCE(ROUND(tu.total_time_s::numeric, 1), 0)   AS \"Total Operating Time\"\nFROM mes.machines m\nCROSS JOIN UNNEST(m.available_tools) AS t(tool_name)\nLEFT JOIN mes.tools tl\n    ON tl.machine_id = m.machine_id\n    AND tl.tool_name = t.tool_name\nLEFT JOIN mes.tool_usage tu\n    ON tu.machine_id = m.machine_id\n    AND tu.tool_name = t.tool_name\nWHERE m.name LIKE 'M1_'\nORDER BY m.machine_id ASC, tl.tool_id ASC;"
      }
     ]
    },
    {
     "title": "Cell 2 Tool Usage",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dataset": "meec00909",
       "rawSql": "SELECT\n    m.name                                             AS \"Machine\",\n    t.tool_name                                        AS \"Tool\",\n    COALESCE(ROUND(tu.total_time_s::numeric, 1), 0)   AS \"Total Operating Time\"\nFROM mes.machines m\nCROSS JOIN UNNEST(m.available_tools) AS t(tool_name)\nLEFT JOIN mes.tools tl\n    ON tl.machine_id = m.machine_id\n    AND tl.tool_name = t.tool_name\nLEFT JOIN mes.tool_usage tu\n    ON tu.machine_id = m.machine_id\n    AND tu.tool_name = t.tool_name\nWHERE m.name LIKE 'M2_'\nORDER BY m.machine_id ASC, tl.tool_id ASC;"
      }
     ]
    },
    {
     "title": "Cell 3 Tool Usage",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dataset": "meec00909",
       "rawSql": "SELECT\n    m.name                                             AS \"Machine\",\n    t.tool_name                                        AS \"Tool\",\n    COALESCE(ROUND(tu.total_time_s::numeric, 1), 0)   AS \"Total Operating Time\"\nFROM mes.machines m\nCROSS JOIN UNNEST(m.available_tools) AS t(tool_name)\nLEFT JOIN mes.tools tl\n    ON tl.machine_id = m.machine_id\n    AND tl.tool_name = t.tool_name\nLEFT JOIN mes.tool_usage tu\n    ON tu.machine_id = m.machine_id\n    AND tu.tool_name = t.tool_name\nWHERE m.name LIKE 'M3_'\nORDER BY m.machine_id ASC, tl.tool_id ASC;"
      }
     ]
    },
    {
     "title": "Cell 4 Tool Usage",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "dataset": "meec00909",
       "rawSql": "SELECT\n    m.name                                             AS \"Machine\",\n    t.tool_name                                        AS \"Tool\",\n    COALESCE(ROUND(tu.total_time_s::numeric, 1), 0)   AS \"Total Operating Time\"\nFROM mes.machines m\nCROSS JOIN UNNEST(m.available_tools) AS t(tool_name)\nLEFT JOIN mes.tools tl\n    ON tl.machine_id = m.machine_id\n    AND tl.tool_name = t.tool_name\nLEFT JOIN mes.tool_usage tu\n    ON tu.machine_id = m.machine_id\n    AND tu.tool_name = t.tool_name\nWHERE m.name LIKE 'M4_'\nORDER BY m.machine_id ASC, tl.tool_id ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Tool Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tool Changes per Machine",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 18 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    m.name                          AS \"Machine\",\n    SUM(ms.tool_changes)            AS \"Tool Changes\"\nFROM mes.machine_stats ms\nJOIN mes.machines m USING (machine_id)\nWHERE ms.recorded_at = (\n    SELECT MAX(recorded_at)\n    FROM mes.machine_stats\n    WHERE machine_id = ms.machine_id\n)\nGROUP BY m.name\nORDER BY m.name;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Operated Work-pieces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "M1a: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M1a'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M2a: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M2a'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M3a: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M3a'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M4a: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M4a'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M1b: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M1b'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M2b: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M2b'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M3a: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M3a'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M4b: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M4b'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M1c: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M1c'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M2c: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M2c'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M3b: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M3b'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "M4c: Operated Work-pieces",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "SELECT\n    /*m.name              AS \"Machine\",*/\n    pl.piece_type       AS \"Piece Type\",\n    COUNT(*)            AS \"Pieces\"\nFROM mes.production_log pl\nLEFT JOIN mes.machines m USING (machine_id)\nWHERE pl.status = 'completed' AND m.name LIKE 'M4c'\nGROUP BY m.name, pl.piece_type\nORDER BY m.name, pl.piece_type;"
      }
     ]
    },
    {
     "title": "Total Operated Work-pieces per Machine",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 31 },
     "targets": [
      {
       "dataset": "sinf252622",
       "rawSql": "/*\nSELECT\n    m.name              AS \"Machine\",\n    COALESCE(ms.pieces_total,0)     AS \"Total Pieces\"\nFROM mes.machines m\nLEFT JOIN mes.machine_stats ms\n    ON ms.machine_id = m.machine_id\n    AND ms.recorded_at = (\n        SELECT MAX(recorded_at)\n        FROM mes.machine_stats\n        WHERE machine_id = m.machine_id\n    )\nORDER BY m.name;\n*/\n\n\nSELECT\n    m.name AS \"Machine\",\n    COUNT(pl.*) AS \"Total Pieces\"\nFROM mes.machines m\nLEFT JOIN mes.production_log pl\n    ON pl.machine_id = m.machine_id\n   AND pl.status = 'completed'\nGROUP BY m.machine_id, m.name\nORDER BY m.name;"
      }
     ]
    }
   ]
  },
  {
   "title": "Unloaded Work-pieces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  }
 ]
}